# Generated by Django 4.1 on 2022-08-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlackList_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('bully_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Bully ID')),
                ('abuseDescription', models.CharField(max_length=1000, verbose_name='Complain Description')),
                ('links', models.URLField(verbose_name='Links')),
                ('anonymity', models.CharField(max_length=20, verbose_name='Anonymity')),
            ],
        ),
    ]
