# Generated by Django 4.1 on 2022-08-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlackList_app', '0003_complain_id_alter_complain_bully_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('userid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlackList_app.users')),
            ],
        ),
    ]
