# Generated by Django 4.1 on 2022-08-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlackList_app', '0005_alter_userpic_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpic',
            name='userid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlackList_app.users'),
        ),
    ]
